import { createHash } from "node:crypto";
import { createExternalSignerIntent } from "./external-signer-intent.js";
import { executionState, assertLocked } from "./execution-state.js";
import { evaluateAgenticBoard } from "./agentic-board.js";
type JsonRpcRequest={jsonrpc:"2.0";id?:string|number|null;method:string;params?:Record<string,unknown>};
const TOOLS=[{name:"get_execution_state",description:"Read deterministic execution state.",inputSchema:{type:"object",properties:{},additionalProperties:false}},{name:"evaluate_opportunity",description:"Evaluate an opportunity through the deterministic agentic board.",inputSchema:{type:"object",required:["chainId","profitable","simulationPassed","netProfitUsd","rpcHealthy","quoteFresh","executionLocked"],properties:{chainId:{type:"integer"},phase:{type:"string"},profitable:{type:"boolean"},simulationPassed:{type:"boolean"},netProfitUsd:{type:"number"},minimumNetProfitUsd:{type:"number"},rpcHealthy:{type:"boolean"},quoteFresh:{type:"boolean"},executionLocked:{type:"boolean"}},additionalProperties:false}},{name:"create_unsigned_intent",description:"Create unsigned external-signer intent; never signs or broadcasts.",inputSchema:{type:"object",required:["lock","to","data"],properties:{lock:{type:"object"},to:{type:"string",pattern:"^0x[0-9a-fA-F]{40}$"},data:{type:"string",pattern:"^0x[0-9a-fA-F]*$"},valueWei:{type:"string"},nowMs:{type:"integer"},ttlMs:{type:"integer"}},additionalProperties:false}}];
function json(v:unknown):string{return JSON.stringify(v,(_k,x)=>typeof x==="bigint"?x.toString():x)}
function auditId(v:unknown):string{return createHash("sha256").update(json(v)).digest("hex")}
function out(id:string|number|null|undefined,v:unknown){return {jsonrpc:"2.0",id:id??null,result:{content:[{type:"text",text:json(v)}]}}}
function err(id:string|number|null|undefined,m:string){return {jsonrpc:"2.0",id:id??null,error:{code:-32000,message:m}}}
function rec(v:unknown):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))throw new Error("INVALID_RECORD");return v as Record<string,unknown>}
function s(r:Record<string,unknown>,k:string){if(typeof r[k]!=="string")throw new Error("INVALID_"+k);return r[k] as string}
function n(r:Record<string,unknown>,k:string){if(typeof r[k]!=="number"||!Number.isFinite(r[k]))throw new Error("INVALID_"+k);return r[k] as number}
function b(r:Record<string,unknown>,k:string){if(typeof r[k]!=="boolean")throw new Error("INVALID_"+k);return r[k] as boolean}
function i(r:Record<string,unknown>,k:string){const v=n(r,k);if(!Number.isInteger(v))throw new Error("INVALID_"+k);return v}
function makeLock(v:unknown){const r=rec(v),d=rec(r.decision);const lock={observationId:s(r,"observationId"),phase:"EXECUTION_LOCKED" as const,chainId:i(r,"chainId"),blockNumber:0n,blockTimestampMs:0,lenderPremiumBlockNumber:0n,planHash:s(r,"planHash"),simulationPassed:b(r,"simulationPassed"),economicInputsVerified:b(r,"economicInputsVerified"),netProfitUsd:n(r,"netProfitUsd"),minimumProfitTokenUnits:BigInt(s(r,"minimumProfitTokenUnits")),decision:{eligible:b(d,"eligible"),reason:s(d,"reason")},gasCostUsd:0,loanToken:s(r,"loanToken"),loanAmount:BigInt(s(r,"loanAmount")),repaymentAmount:BigInt(s(r,"repaymentAmount")),lenderSourceId:s(r,"lenderSourceId"),executionAuthorization:0 as const,liveSigning:false,broadcastEnabled:false};if(!lock.simulationPassed||!lock.economicInputsVerified||!lock.decision.eligible||lock.netProfitUsd<2)throw new Error("DETERMINISTIC_LOCK_REQUIREMENTS_NOT_MET");if(b(r,"liveSigning")||b(r,"broadcastEnabled")||i(r,"executionAuthorization")!==0)throw new Error("EXECUTION_LOCK_POLICY_VIOLATION");return lock}
async function handle(q:JsonRpcRequest){if(q.method==="initialize")return out(q.id,{protocolVersion:"2025-06-18",capabilities:{tools:{}},serverInfo:{name:"flash-arb7-hermes-control",version:"0.1.0"}});if(q.method==="notifications/initialized")return null;if(q.method==="ping")return out(q.id,{ok:true});if(q.method==="tools/list")return out(q.id,{tools:TOOLS});if(q.method!=="tools/call")throw new Error("METHOD_NOT_FOUND");const p=rec(q.params),name=s(p,"name"),a=p.arguments??{};if(name==="get_execution_state"){assertLocked();return out(q.id,{correlationId:String(q.id??"none"),auditId:auditId(executionState),state:executionState})}if(name==="evaluate_opportunity"){const x=rec(a);const input={chainId:i(x,"chainId"),phase:typeof x.phase==="string"?x.phase:"UNKNOWN",profitable:b(x,"profitable"),simulationPassed:b(x,"simulationPassed"),netProfitUsd:n(x,"netProfitUsd"),minimumNetProfitUsd:x.minimumNetProfitUsd===undefined?undefined:n(x,"minimumNetProfitUsd"),rpcHealthy:b(x,"rpcHealthy"),quoteFresh:b(x,"quoteFresh"),executionLocked:b(x,"executionLocked")};const state=evaluateAgenticBoard(input);return out(q.id,{correlationId:String(q.id??"none"),auditId:auditId({input,state}),state})}if(name==="create_unsigned_intent"){const x=rec(a),lock=makeLock(x.lock),intent=createExternalSignerIntent(lock,s(x,"to"),s(x,"data"),x.valueWei===undefined?0n:BigInt(s(x,"valueWei")),x.nowMs===undefined?Date.now():i(x,"nowMs"),x.ttlMs===undefined?30000:i(x,"ttlMs"));return out(q.id,{correlationId:String(q.id??"none"),auditId:auditId(intent),intent,execution:{authorization:0,signing:false,broadcast:false}})}throw new Error("UNKNOWN_TOOL")}
let buffer="";process.stdin.setEncoding("utf8");process.stdin.on("data",(chunk:string)=>{buffer+=chunk;let p=buffer.indexOf("\n");while(p>=0){const line=buffer.slice(0,p).trim();buffer=buffer.slice(p+1);if(line)void handle(JSON.parse(line)).then(v=>{if(v)process.stdout.write(json(v)+"\n")}).catch(e=>process.stdout.write(json(err(undefined,e instanceof Error?e.message:"INTERNAL_ERROR"))+"\n"));p=buffer.indexOf("\n")}});