#!/usr/bin/env bash
set -euo pipefail

load_dotenv_value(){ local key="$1" value file; for file in .env nano.env; do [[ -f "$file" ]] || continue; value="$(grep -E "^[[:space:]]*(export[[:space:]]+)?${key}=" "$file" | tail -n 1 | sed -E "s/^[[:space:]]*(export[[:space:]]+)?${key}=//; s/^[[:space:]]*//; s/[[:space:]]*$//")"; value="${value%\"}"; value="${value#\"}"; value="${value%\'}"; value="${value#\'}"; [[ -n "$value" ]] && printf '%s' "$value" && return 0; done; return 0; }
is_placeholder(){ local v="$1"; [[ -z "$v" || "$v" == *'\${'* || "$v" == *'YOUR_'* || "$v" == *'PASTE_YOUR_'* || "$v" == *'replace_with_'* || "$v" == *'$ALCHEMY_API_KEY'* ]]; }
if [[ -z "${ALCHEMY_API_KEY:-}" ]]; then _k="$(load_dotenv_value ALCHEMY_API_KEY || true)"; [[ -n "$_k" ]] && export ALCHEMY_API_KEY="$_k"; unset _k; fi
for v in ETH_RPC_URL BSC_RPC_URL BASE_RPC_URL ARBITRUM_RPC_URL AVAX_RPC_URL CRONOS_RPC_URL SONIC_RPC_URL; do if [[ -z "${!v:-}" ]]; then _x="$(load_dotenv_value "$v" || true)"; [[ -n "$_x" ]] && export "$v=$_x"; unset _x; fi; done
if [[ -n "${ALCHEMY_API_KEY:-}" ]]; then case "$ALCHEMY_API_KEY" in YOUR_*|PASTE_YOUR_*|replace_with_*) echo 'ERROR: ALCHEMY_API_KEY is a placeholder.' >&2; exit 1;; esac; : "${ETH_RPC_URL:=https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}}"; : "${BSC_RPC_URL:=https://bnb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}}"; : "${BASE_RPC_URL:=https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}}"; : "${ARBITRUM_RPC_URL:=https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}}"; : "${AVAX_RPC_URL:=https://avax-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}}"; : "${CRONOS_RPC_URL:=https://cronos-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}}"; : "${SONIC_RPC_URL:=https://sonic-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}}"; export ETH_RPC_URL BSC_RPC_URL BASE_RPC_URL ARBITRUM_RPC_URL AVAX_RPC_URL CRONOS_RPC_URL SONIC_RPC_URL; fi
for v in ETH_RPC_URL BSC_RPC_URL BASE_RPC_URL ARBITRUM_RPC_URL AVAX_RPC_URL CRONOS_RPC_URL SONIC_RPC_URL; do x="${!v:-}"; if is_placeholder "$x"; then echo "ERROR: $v is unset or placeholder." >&2; exit 1; fi; done
unset v x
echo 'Alchemy RPC environment prepared for 7 EVM networks (credentials not printed).'